src/Lead2Change.Web.Ui/Controllers/AdminController.cs
using Lead2Change.Domain.Constants;
using Lead2Change.Domain.Models;
using Lead2Change.Services.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lead2Change.Web.Ui.Controllers
{
    public class AdminController : _BaseController
    {
        public AdminController(IUserService identityService, RoleManager<AspNetRoles> roleManager, UserManager<AspNetUsers> userManager, SignInManager<AspNetUsers> signInManager) : base(identityService, roleManager, userManager, signInManager)
        {

        }


        public async Task<IActionResult> Index()
        {
            if (User.IsInRole(StringConstants.RoleNameAdmin))
            {
                var users = await UserManager.GetUsersInRoleAsync(StringConstants.RoleNameAdmin);
                return View(users);
            }
            else
            {
                return Error("403: Forbidden");
            }
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var user = await UserManager.FindByIdAsync(id.ToString());

            // Check for bad id or student
            if (id == Guid.Empty )
            {
                return Error("400: Bad Request");
            }

            await UserManager.DeleteAsync(user);
            // Delete Student
            
            return RedirectToAction("Index");
        }
    }
}

src/Lead2Change.Web.Ui/Controllers/CoachesController.cs
using Lead2Change.Domain.ViewModels;
using Lead2Change.Services.Identity;
using Lead2Change.Services.Coaches;
using Microsoft.AspNetCore.Mvc;
using Lead2Change.Domain.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Lead2Change.Domain.Constants;
using Lead2Change.Services.Students;
using Microsoft.AspNetCore.Authorization;

namespace Lead2Change.Web.Ui.Controllers
{
    [Authorize(Roles = StringConstants.RoleNameAdmin + "," + StringConstants.RoleNameCoach)]
    public class CoachesController : _BaseController
    {
        ICoachService _coachService;
        IStudentService _studentService;

        public CoachesController(IUserService identityService, ICoachService coachService, IStudentService studentService, RoleManager<AspNetRoles> roleManager, UserManager<AspNetUsers> userManager, SignInManager<AspNetUsers> signInManager) : base(identityService, roleManager, userManager, signInManager)
        {
            _coachService = coachService;
            _studentService = studentService;
        }

        [Authorize(Roles = StringConstants.RoleNameAdmin)]
        public async Task<IActionResult> Index()
        {
            return View(await _coachService.GetCoaches());
        }
        public async Task<IActionResult> AssignedIndex()
        {
            return View(await _coachService.GetCoaches());
        }


        [Authorize(Roles = StringConstants.RoleNameAdmin)]
        public async Task<IActionResult> Delete(Guid id)
        {
            var coach = await _coachService.GetCoach(id);
            if (id == Guid.Empty || coach == null)
            {
                return Error("400: Bad Request");
            }

            coach.Students = await _studentService.GetCoachStudents(id);
            foreach (var item in coach.Students)
            {
                item.CoachId = null;
            }

            await _coachService.Delete(coach);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var coachescontainer = await _coachService.GetCoach(id);

            if (id == Guid.Empty || coachescontainer == null)
            {
                return Error("400: Bad Request");
            }

            CoachViewModel model = new CoachViewModel();

            if (coachescontainer != null)
            {
                model.Id = coachescontainer.Id;
                model.CoachFirstName = coachescontainer.CoachFirstName;
                model.CoachLastName = coachescontainer.CoachLastName;
                model.CoachEmail = coachescontainer.CoachEmail;
                model.CoachPhoneNumber = coachescontainer.CoachPhoneNumber;
                model.Students = new List<Student>();
                model.Active = coachescontainer.Active;
            }

            model.Students = await _studentService.GetCoachStudents(id);

            return View(model);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var coach = await _coachService.GetCoach(id);

            if (id == Guid.Empty || coach == null)
            {
                return Error("400: Bad Request");
            }

            CoachViewModel list = new CoachViewModel()
            {
                Id = coach.Id,
                CoachFirstName = coach.CoachFirstName,
                CoachLastName = coach.CoachLastName,
                CoachPhoneNumber = coach.CoachPhoneNumber,
                CoachEmail = coach.CoachEmail,
                Active = coach.Active
            };
            return View(list);
        }

        public async Task<IActionResult> Create()
        {
            var user = await UserManager.GetUserAsync(User);
            if (User.IsInRole(StringConstants.RoleNameCoach) && user.AssociatedId != Guid.Empty)
            {
                return Error("403: You are not authorized to view this page.");
            }

            return View(new CoachViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CoachViewModel model)
        {
            if (!SignInManager.IsSignedIn(User))
            {
                return Error("401: Unauthorized");
            }

            var user = await UserManager.GetUserAsync(User);
            if (User.IsInRole(StringConstants.RoleNameCoach) && user.AssociatedId != Guid.Empty)
            {
                return Error("403: You are not authorized to view this page.");
            }

            if (ModelState.IsValid)
            {
                    Coach coach = new Coach()
                    {
                        CoachFirstName = model.CoachFirstName,
                        CoachLastName = model.CoachLastName,
                        CoachEmail = model.CoachEmail,
                        CoachPhoneNumber = model.CoachPhoneNumber,
                        Students = new List<Student>(),
                        Active = true
                    };
                    var result = await _coachService.Create(coach);
                    if (User.IsInRole(StringConstants.RoleNameCoach))
                    {
                        user.AssociatedId = result.Id;
                        await _coachService.Update(result);
                        return RedirectToAction("Index", "Students");
                }

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<IActionResult> Update(Coach model)
        {
            if (ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    Coach list = new Coach()
                    {
                        Id = model.Id,
                        CoachFirstName = model.CoachFirstName,
                        CoachLastName = model.CoachLastName,
                        CoachEmail = model.CoachEmail,
                        CoachPhoneNumber = model.CoachPhoneNumber,
                        Active = model.Active
                    };
                    var student = await _coachService.Update(list);
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // TODO: Need to add "AddStudent" method to Service
        // Change StudentService to change the CoachId
        public async Task<IActionResult> AssignStudent(Guid studentId, Guid coachId)
        {
            var coach = await _coachService.GetCoach(coachId); //check coach exists
            var student = await _studentService.GetStudent(studentId);

            student.CoachId = coachId;

            var student1 = await _studentService.Update(student);
            return RedirectToAction("AssignStudentIndex", new { id = coach.Id });
        }

        public async Task<IActionResult> AssignStudentIndex(Guid id)
        {
            Coach tempCoach = await _coachService.GetCoach(id);
            AssignStudentViewModel assignStudentViewModel = new AssignStudentViewModel()
            {
                UnassignedStudents = await _studentService.GetUnassignedStudents(),
                CurrentCoach = tempCoach
            };
            return View(assignStudentViewModel);
        }

        public async Task<IActionResult> UnassignStudent(Guid studentId)
        {
            var student = await _studentService.GetStudent(studentId);
            var tempCoachId = student.CoachId;
            student.CoachId = null;
            var student1 = await _studentService.Update(student);
            return RedirectToAction("CoachesStudents", new { id = tempCoachId });
        }
        public async Task<IActionResult> CoachesStudents(Guid id)
        {
            var user = await UserManager.GetUserAsync(User);
            if (id == Guid.Empty) id = user.AssociatedId;

            CoachViewModel model = new CoachViewModel();
            var coachescontainer = await _coachService.GetCoach(id); //check for coachescontainer=null, and all other fields

            if (id == Guid.Empty || coachescontainer == null)
            {
                return Error("400: Bad Request");
            }

            model.Id = coachescontainer.Id;
            model.CoachFirstName = coachescontainer.CoachFirstName;
            model.CoachLastName = coachescontainer.CoachLastName;
            model.CoachEmail = coachescontainer.CoachEmail;
            model.CoachPhoneNumber = coachescontainer.CoachPhoneNumber;
            model.Students = new List<Student>();
            model.Active = coachescontainer.Active;


            model.Students = await _studentService.GetCoachStudents(id);


            return View(model);
        }
        public async Task<IActionResult> InactiveCoach(Guid coachId)
        {
            var coach = await _coachService.GetCoach(coachId);
            coach.Active = false;
            var tempList = await _studentService.GetCoachStudents(coachId);
            foreach (Student s in tempList)
            {
                await UnassignStudent(s.Id);
            }
            var coach1 = await _coachService.Update(coach);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ActiveCoach(Guid coachId)
        {
            var coach = await _coachService.GetCoach(coachId);
            coach.Active = true;
            var coach1 = await _coachService.Update(coach);
            return RedirectToAction("Index");
        }
    }
}

src/Lead2Change.Web.Ui/Controllers/QuestionsController.cs
using Lead2Change.Web.Ui.Models;
using Lead2Change.Services.Questions;
using Microsoft.AspNetCore.Mvc;
using Lead2Change.Domain.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lead2Change.Domain.Models;
using Lead2Change.Domain.Constants;
using Lead2Change.Domain.Models;
using Lead2Change.Domain.ViewModels;
using Lead2Change.Services.CareerDeclarationService;
using Lead2Change.Services.Identity;
using Lead2Change.Services.Students;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Lead2Change.Web.Ui.Controllers
{
    [Authorize(Roles = StringConstants.RoleNameAdmin + "," + StringConstants.RoleNameCoach)]
    public class QuestionsController : _BaseController
    {
        private IQuestionsService QuestionsService;
        private IStudentService _studentService;

        public QuestionsController(IQuestionsService questionsService, IUserService identityService, ICareerDeclarationService careerDeclarationService, IStudentService studentService, RoleManager<AspNetRoles> roleManager, UserManager<AspNetUsers> userManager, SignInManager<AspNetUsers> signInManager) : base(identityService, roleManager, userManager, signInManager)
        {
            this.QuestionsService = questionsService;
            _studentService = studentService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await QuestionsService.GetQuestions());
        }
        public async Task<IActionResult> Create()
        {
            return View(new QuestionsViewModel());
        }
        public async Task<IActionResult> ArchivedQuestions()
        {
            return View(await QuestionsService.GetArchivedQuestions());
        }

        [HttpPost]

        public async Task<IActionResult> Register(QuestionsViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (!String.IsNullOrEmpty(model.QuestionString))
                {
                    Question question = new Question()
                    {
                        QuestionString = model.QuestionString,
                        Id = model.Id,
                        QuestionInInterviews = model.QuestionInInterviews
                    };
                    var result = await QuestionsService.Create(question);
                }
                
                if (Request.Form["RedirectCreateView"].Equals("Create and New")) { return RedirectToAction("Create"); }
                else {return RedirectToAction("Index");}

            }
            return View("Create", model);
        }
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await QuestionsService.GetQuestion(id);
            QuestionsViewModel question = new QuestionsViewModel()
            {
                QuestionString = result.QuestionString,
                Id = id,
                QuestionInInterviews = result.QuestionInInterviews
            };
            return View(question);
        }
        public async Task<IActionResult> ArchiveEdit(Guid id)
        {
            var result = await QuestionsService.GetQuestion(id);
            QuestionsViewModel question = new QuestionsViewModel()
            {
                QuestionString = result.QuestionString,
                Id = id,
                QuestionInInterviews = result.QuestionInInterviews
            };
            return View(question);
        }

        public async Task<IActionResult> Update(Question model)
        {
            if (ModelState.IsValid)
            {
                if (!String.IsNullOrEmpty(model.QuestionString))
                {
                    var Question = await QuestionsService.Update(model);

                }

                return RedirectToAction("Index");
            }
            return View(model);
        }
        public async Task<IActionResult> Details(Guid id)
        {
            var result = await QuestionsService.GetQuestion(id);
            QuestionsViewModel question = new QuestionsViewModel()
            {
                QuestionString = result.QuestionString,
                Id = id,
                QuestionInInterviews = result.QuestionInInterviews
            };
            return View(question);
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            var question = await QuestionsService.GetQuestion(id);
            await QuestionsService.Delete(question);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> PermanentDelete(Guid id)
        {
            var question = await QuestionsService.GetQuestion(id);
            await QuestionsService.PermanentDelete(question);
            return RedirectToAction("ArchivedQuestions", new { questionID = question.Id });
        }
    }
}

src/Lead2Change.Web.Ui/Views/Shared/_Layout.cshtml
@using Lead2Change.Domain.Constants;
@using Microsoft.AspNetCore.Identity
@using Lead2Change.Domain.Models
@inject SignInManager<AspNetUsers> SignInManager
@inject UserManager<AspNetUsers> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @StringConstants.BASE_PAGE_TITLE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="\Images\Lead2ChangeIcon.png">
</head>
<body>  
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3" style="background-color: #1e202d">
            <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img id="navbarLogo" src="~/Images/Lead2ChangeLogo.png" /></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        
                        @* <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                        @if (SignInManager.IsSignedIn(User))
                        {
                            @if (User.IsInRole(StringConstants.RoleNameStudent))
                            {
                                <li class="nav-item col-sm-4">
                                    @Html.ActionLink("Student", "Details", "Students", new { studentId = UserManager.GetUserAsync(User).Result.AssociatedId }, new { @class = "nav-link text-dark" })
                                </li>
                                <li class="nav-item col-sm-4">
                                    @Html.ActionLink("Goals", "Index", "Goals", new { studentID = UserManager.GetUserAsync(User).Result.AssociatedId }, new { @class = "nav-link text-dark" })
                                </li>
                                <li class="nav-item col-sm-4">
                                    @Html.ActionLink("Career", "Details", "CareerDeclaration", new { studentId = UserManager.GetUserAsync(User).Result.AssociatedId }, new { @class = "nav-link text-dark" })
                                </li>
                            }
                            @if (User.IsInRole(StringConstants.RoleNameCoach))
                            {
                                <li class="nav-item col-sm-4">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Coaches" asp-action="CoachesStudents">My Students</a>
                                </li>
                                <li class="nav-item col-sm-4">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Interviews" asp-action="Index">Interviews</a>
                                </li>
                                <li class="nav-item col-sm-4">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Questions" asp-action="Index">Questions</a>
                                </li>
                            }
                            @if (User.IsInRole(StringConstants.RoleNameAdmin))
                            {
                                <li class="nav-item col-sm-2">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Students" asp-action="Index">Active Students</a>
                                </li>
                                <li class="nav-item col-sm-2">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Students" asp-action="InactiveIndex" >Inactive Students</a>
                                </li>
                                <li class="nav-item col-sm-2">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Coaches" asp-action="Index">Coaches</a>
                                </li>
                                <li class="nav-item col-sm-2">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Interviews" asp-action="Index">Interviews</a>
                                </li>
                                <li class="nav-item col-sm-2">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Questions" asp-action="Index">Questions</a>
                                </li>
                                <li class="nav-item col-sm-2">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="Index">Admins</a>
                                </li>
                            }
                        } else
                            {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Students" asp-action="InterestForm">Fill Out the Interest Form</a>
                            </li>
                            }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Lead2Change.Web.Ui - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/searchbar.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>