src/Lead2Change.Web.Ui/Controllers/GoalsController.cs
using Lead2Change.Web.Ui.Models;
using Lead2Change.Services.Goals;
using Lead2Change.Services.Students;
using Microsoft.AspNetCore.Mvc;
using Lead2Change.Domain.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Lead2Change.Domain.Models;
using Lead2Change.Services.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Lead2Change.Domain.Constants;

namespace Lead2Change.Web.Ui.Controllers
{
    [Authorize(Roles = StringConstants.RoleNameAdmin + "," + StringConstants.RoleNameCoach)]
    public class GoalsController : _BaseController
    {
        private IGoalsService GoalsService;
        private IStudentService StudentService;
        public GoalsController(IUserService identityService, IGoalsService goalsService, IStudentService studentService, RoleManager<AspNetRoles> roleManager, UserManager<AspNetUsers> userManager, SignInManager<AspNetUsers> signInManager) : base(identityService, roleManager, userManager, signInManager)
        {
            this.GoalsService = goalsService;
            this.StudentService = studentService;
        }
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await GoalsService.GetGoal(id);
            GoalViewModel goal = new GoalViewModel()
            {
                Id = id,
                StudentId = result.StudentId,
                GoalSet = result.GoalSet,
                DateGoalSet = result.DateGoalSet,
                SEL = result.SEL.Split(","),
                GoalReviewDate = result.GoalReviewDate,
                WasItAccomplished = result.WasItAccomplished,
                Explanation = result.Explanation,             
            };
            return View(goal);
        }

        public async Task<IActionResult> Update(GoalViewModel model)
        {
            // Prevents null exceptions from no SEL input being selected
            string goalSEL = (model.SEL == null) ? "" : String.Join(", ", model.SEL);


            Goal goal = new Goal
            {
                GoalSet = model.GoalSet,
                StudentId = model.StudentId,
                Id = model.Id,
                DateGoalSet = model.DateGoalSet,
                SEL = goalSEL,
                GoalReviewDate = model.GoalReviewDate,
                WasItAccomplished = model.WasItAccomplished,
                Explanation = model.Explanation,
            };
            if (ModelState.IsValid)
            {
                var Goal = await GoalsService.Update(goal);
                return RedirectToAction("Index", new { studentID = model.StudentId });
            }
            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var goal = await GoalsService.GetGoal(id);

            if (goal == null)
            {
                return RedirectToAction("Create");
            }

            if (!await CanEditStudent(goal.StudentId))
            {
                return Error("403: Not authorized to view this student.");
            }
            GoalViewModel viewModel = new GoalViewModel()
            {
                Id = id,
                StudentId = goal.StudentId,
                DateGoalSet = goal.DateGoalSet,
                GoalSet = goal.GoalSet,
                SEL = goal.SEL.Split(",") ,
                GoalReviewDate = goal.GoalReviewDate,
                WasItAccomplished = goal.WasItAccomplished,
                Explanation = goal.Explanation
            };
            return View(viewModel);
        }

        /**
         * Accepts the Guid of the student that the goal is being created for
         */
        public async Task<IActionResult> Create(Guid studentID)
        {
            return View(new GoalViewModel()
            {
                StudentId = studentID,
                // This changes the initial date displayed in the chooser
                DateGoalSet = DateTime.Today,
                GoalReviewDate = DateTime.Today,
            }) ;
        }
        [HttpPost]
        public async Task<IActionResult> Register(GoalViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                // Checks to prevent null exception errors
                string goalSEL = (viewModel.SEL == null) ? "" : string.Join(", ", viewModel.SEL);
                Goal goal = new Goal()
                {
                    GoalSet = viewModel.GoalSet,
                    StudentId = viewModel.StudentId,
                    Id = viewModel.Id,
                    DateGoalSet = viewModel.DateGoalSet,
                    SEL = goalSEL,
                    GoalReviewDate = viewModel.GoalReviewDate,
                    WasItAccomplished = viewModel.WasItAccomplished,
                    Explanation = viewModel.Explanation,
                };
                // TODO: Create StudentId on user Registration
                var result = await GoalsService.Create(goal);
                return RedirectToAction("Index", new { studentID = result.StudentId });
            }
            return View("Create", viewModel);
        }

        /**
         * Note that Index takes in a studentID (it displays the goals for that student)
         * And returns a special view model which contains a list of GoalViewModels
         * And the studentID
         */
        public async Task<IActionResult> Index(Guid studentID)
        {
            List<GoalViewModel> result = new List<GoalViewModel>();
            List<Goal> goals = await GoalsService.GetGoals(studentID);
            var student1 = await StudentService.GetStudent(studentID);
            
            foreach (Goal goal in goals)
            {
                string example = goal.SEL;
                string noSpace = String.Concat(example.Where(c => !Char.IsWhiteSpace(c)));
                result.Add(new GoalViewModel()
                {
                    GoalSet = goal.GoalSet,
                    Id = goal.Id,
                    StudentId = goal.StudentId,
                    DateGoalSet = goal.DateGoalSet,
                    SEL = noSpace.Split(","),
                    GoalReviewDate = goal.GoalReviewDate,
                    WasItAccomplished = goal.WasItAccomplished,
                    Explanation = goal.Explanation

                });
            }

            return View(new GoalsAndIDViewModel(studentID)
            {
                GoalModels = result,
                Name = student1.StudentFirstName,
                isStudentActive = student1.Active,
            }) ;
        
        }

        /**
         * Handles the deletion of a goal based off the goal's id
         */
        public async Task<IActionResult> Delete(Guid id, Guid studentID)
        {
            var goal = await GoalsService.GetGoal(id);
            await GoalsService.Delete(goal);
            return RedirectToAction("Index", new { studentID = goal.StudentId });
        }

    }
}

src/Lead2Change.Web.Ui/Controllers/StudentsController.cs
using Lead2Change.Domain.ViewModels;
using Lead2Change.Services.Identity;
using Lead2Change.Services.Students;
using Microsoft.AspNetCore.Mvc;
using Lead2Change.Domain.Models;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Lead2Change.Web.Ui.Models;

using Lead2Change.Domain.Constants;

using Microsoft.AspNetCore.Authorization;
using Lead2Change.Services.Coaches;

namespace Lead2Change.Web.Ui.Controllers
{
    public class StudentsController : _BaseController
    {
        IStudentService _studentService;
        ICoachService _coachService;
        static bool SendToAdmin = false;
        static string AdminEmail = "";
        public StudentsController(IUserService identityService, IStudentService studentService, ICoachService coachService, RoleManager<AspNetRoles> roleManager, UserManager<AspNetUsers> userManager, SignInManager<AspNetUsers> signInManager) : base(identityService, roleManager, userManager, signInManager)
        {
            _studentService = studentService;
            _coachService = coachService;
        }

        public async Task<IActionResult> Index()
        {
            if (!SignInManager.IsSignedIn(User))
            {
                return Redirect("/Identity/Account/Login?returnUrl=/Students");
            }

            if (User.IsInRole(StringConstants.RoleNameStudent))
            {
                return Error("403: You are not authorized to view this page.");
            }

            var user = await UserManager.GetUserAsync(User);
            if (User.IsInRole(StringConstants.RoleNameCoach))
            {
                /*if (user.AssociatedId != Guid.Empty)
                    return View(await _studentService.GetCoachStudents(user.AssociatedId));
                else
                    return RedirectToAction("Create", "Coaches");
                */
                //above is commented out because coaches should be viewing their students through the separate CoachesStudents
                return Error("403: You are not authorized to view this page.");
            }
            else if (User.IsInRole(StringConstants.RoleNameAdmin))
            {
                return View(await _studentService.GetActiveStudents());               

            }

            return Error("400: Bad Request");
        }

        public async Task<IActionResult> InactiveIndex()
        {
            if (User.IsInRole(StringConstants.RoleNameAdmin))

            {

                return View(await _studentService.GetInactiveStudents());

            }

            return Error("403: You are not authorized to view this page.");
        }

        public async Task<IActionResult> Archive(Guid studentId, bool state = false)
        {
            // Check SignedIn
            if (!SignInManager.IsSignedIn(User))
            {
                return Error("401: Unauthorized");
            }

            // Check Permissions
            /*
             *  Students: Not Allowed
             *  Coach: Not Allowed
             *  Admin: Allowed
             */
            if (!User.IsInRole(StringConstants.RoleNameAdmin))
            {
                return Error("403: Forbidden");
            }

            // Find Student
            var student = await _studentService.GetStudent(studentId);

            // Check for bad id or student
            if (studentId == Guid.Empty || student == null)
            {
                return Error("400: Bad Request");
            }

            // Delete Student
            student.Active = state;
            await _studentService.Update(student);
            return RedirectToAction(state ? "InactiveIndex" : "Index");
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            // Check SignedIn
            if (!SignInManager.IsSignedIn(User))
            {
                return Error("401: Unauthorized");
            }

            // Check Permissions
            /*
             *  Students: Not Allowed
             *  Coach: Not Allowed
             *  Admin: Allowed
             */
            if (!User.IsInRole(StringConstants.RoleNameAdmin))
            {
                return Error("403: Forbidden");
            }

            // Find Student
            var student = await _studentService.GetStudent(id);

            // Check for bad id or student
            if (id == Guid.Empty || student == null)

            {

                return Error("400: Bad Request");

            }

            // Delete Student
            await _studentService.Delete(student);
            return RedirectToAction("InactiveIndex");//should only be able to delete from here
        }

        public async Task<IActionResult> Register()
        {
            // Check SignedIn
            if (!SignInManager.IsSignedIn(User))
            {
                return Error("401: Unauthorized");
            }

            // Check Permissions
            /*
             *  Students: Allowed
             *  Coach: Not Allowed
             *  Admin: Allowed
             */
            if (User.IsInRole(StringConstants.RoleNameCoach))
            {
                return Error("403: Forbidden");
            }

            // Find user
            var user = await UserManager.GetUserAsync(User);

            // Check if user owns a student
            if (user.AssociatedId != Guid.Empty)
            {
                return RedirectToAction("Details", new { studentId = user.AssociatedId });
            }

            return View(new RegistrationViewModel()
            {
                // This changes the initial date displayed in the chooser
                StudentDateOfBirth = DateTime.Today,
                PACTTestDate = DateTime.Today,
                PSATTestDate = DateTime.Today,
                SATTestDate = DateTime.Today,
                ACTTestDate = DateTime.Today,
                StudentSignatureDate = DateTime.Today,
                ParentSignatureDate = DateTime.Today,
            });
        }

        public async Task<IActionResult> Details(Guid studentId)
        {
            // Check SignedIn
            if (!SignInManager.IsSignedIn(User))
            {
                return Error("401: Unauthorized");
            }

            // Redirect to Register if Guid is empty
            if (studentId == Guid.Empty)
            {
                return RedirectToAction("Register");
            }

            // Check Permissions
            /*
             *  Students: Allowed only if it is them
             *  Coach: Allowed only if student is owned by coach
             *  Admin: Allowed
             */
            // TODO: Error only if coach does not own the student

            // Find Student
            var student = await _studentService.GetStudent(studentId);

            if (User.IsInRole(StringConstants.RoleNameCoach))
            {
                var user = await UserManager.GetUserAsync(User);
                if (student.CoachId != user.AssociatedId) return Error("403: Forbidden");
            }
            else if (User.IsInRole(StringConstants.RoleNameStudent))
            {
                // Find user
                var user = await UserManager.GetUserAsync(User);

                // Check that studentId is the AssociatedId of the user
                if (user.AssociatedId == Guid.Empty || user.AssociatedId != studentId)
                {
                    return Error("403: Forbidden");
                }
            }



            // Check for bad student
            if (student == null)
            {
                return Error("400: Bad Request");
            }

            //check for null
            //Caclculate age:
            var coachcontainer = new Coach();
            if (student.CoachId.HasValue)
            {
                coachcontainer = await _coachService.GetCoach(student.CoachId.Value);
            }
            var age = DateTime.Now.Year - student.StudentDateOfBirth.Year;
            if (DateTime.Now.Month < student.StudentDateOfBirth.Month)
            {
                age--;
            }
            if (DateTime.Now.Month == student.StudentDateOfBirth.Month)
            {
                if (DateTime.Now.Day < student.StudentDateOfBirth.Day)
                {
                    age--;
                }
            }
            // Create a new viewModel
            RegistrationViewModel viewModel = new RegistrationViewModel()
            {
                Id = student.Id,
                isAccepted =student.Accepted,
                isDeclined = student.Declined,
                StudentFirstName = student.StudentFirstName,
                StudentLastName = student.StudentLastName,
                StudentDateOfBirth = student.StudentDateOfBirth,
                Age = age,
                //using calculated age above
                StudentAddress = student.StudentAddress,
                StudentApartmentNumber = student.StudentApartmentNumber,
                StudentCity = student.StudentCity,
                StudentState = student.StudentState,
                StudentZipCode = student.StudentZipCode,
                StudentHomePhone = student.StudentHomePhone,
                StudentCellPhone = student.StudentCellPhone,
                StudentEmail = student.StudentEmail,
                StudentCareerPath = student.StudentCareerPath,
                StudentCareerInterest = student.StudentCareerInterest,
                CoachName = student.CoachId.HasValue ? coachcontainer.CoachFirstName + " " + coachcontainer.CoachLastName : "Unassigned",

                ParentFirstName = student.ParentFirstName,
                ParentLastName = student.ParentLastName,

src/Lead2Change.Web.Ui/Views/Students/ApplyingStudentsIndex.cshtml
@model List<Lead2Change.Domain.Models.Student>
@*
    ViewData["Title"] = "StudentsApplyingIndex";
*@
<div class="row orangeHeader full-width mb-sm-3">
    <div class="col-sm-12">
        <h1 class="text-center"><strong>APPLYING STUDENTS</strong></h1>
    </div>
</div>
<div class="container">

    <table class="table sortable" id="myTable">
        <thead>
            <tr>
                <th scope="col">Last Name</th>
                <th scope="col">First Name</th>
                <th scope="col">Date Of Birth</th>
                <th scope="col">Email</th>
                <th scope="col">Cell Phone</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.StudentLastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StudentFirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StudentDateOfBirth)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StudentEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StudentCellPhone)
                    </td>
                    <td>
                        <div>
                            <div>
                                @Html.ActionLink("Edit", "Edit", new { studentId = item.Id })
                            </div>

                            <div>
                                @Html.ActionLink("Details", "Details", new { studentId = item.Id })
                            </div>
                            <div>
                                @Html.ActionLink("Accept Student", "AcceptStudent", new { studentId = item.Id })
                            </div>
                        </div>
                    </td>
                </tr>

            }
        </tbody>
    </table>
</div>

src/Lead2Change.Web.Ui/Views/Students/InactiveIndex.cshtml
@using Lead2Change.Domain.Constants
@model List<Lead2Change.Domain.Models.Student>
@*
    ViewData["Title"] = "Index";
*@

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


<div class="container">
    <div class="row blueHeader full-width mb-sm-3">
        <div class="col-sm-12">
            <h1 class="text-center"><strong>INACTIVE STUDENTS</strong></h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 searchbar ml-auto">
            <input type="text" id="myInput" onkeyup="searchFilter()" placeholder="Search for students.." class="tableInput searchbar__input" align="right">
            <button type="button" class="searchbar__button">
                <i class="material-icons">search</i>
            </button>
        </div>
    </div>
    <div class="col-sm-12">
        <table class="table table-striped table-hover table-responsive-sm fixedTable mt-sm-3 mb-0 shadow-lg">
            <thead class="blueStyle">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Date Of Birth</th>
                    <th scope="col">Email</th>
                    <th scope="col">Parent Name</th>
                    <th scope="col">Parent Email</th>
                    <th scope="col">Options</th>
                </tr>
            </thead>
        </table>
        <div class="tableScroll shadow-lg">
            <table class="table table-striped table-hover table-responsive-sm fixedTable mb-0 tableMin" id="myTable">
                <thead class="blueStyle d-none">
                    <tr>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {

                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StudentLastName), @Html.DisplayFor(modelItem => item.StudentFirstName)
                                </td>
                                <td>
                                    @*@Html.DisplayFor(modelItem => item.StudentDateOfBirth.ToString("d"))*@
                                    @*@Model.modelItem => item.StudentDateOfBirth.ToString("d")*@
                                    @Convert.ToDateTime(item.StudentDateOfBirth).ToString("MM/dd/yyyy")
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StudentEmail)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ParentLastName), @Html.DisplayFor(modelItem => item.ParentFirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ParentEmail)
                                </td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn  btn-block orangeBtn mb-sm-2 dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Options</button>
                                        <div class="dropdown-menu">
                                            <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Edit","Students", new { studentId = item.Id })'">Edit</button>
                                            <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Details","Students", new { studentId = item.Id })'">Details</button>
                                            <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Index","Goals", new { studentId = item.Id })'">Student Goals</button>
                                            
                                            @if (item.CareerDeclarationId == Guid.Empty)
                                            {
                                                <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Create","CareerDeclaration", new { studentId = item.Id })'">Add Career</button>
                                            }
                                            else
                                            {
                                                <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Details","CareerDeclaration", new { studentId = item.Id })'">View Career</button>
                                            }
                                            <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Archive","Students", new { studentId = item.Id, state = true })'">Un-Archive</button>
                                            <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Delete","Students", new { id = item.Id })'">Delete</button>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }}
                </tbody>
            </table>
        </div>
    </div>

    @if (User.IsInRole(StringConstants.RoleNameAdmin))
    {
<div>
    <a asp-action="InterestForm"><b>Register a new student</b></a>
</div>}
</div>

src/Lead2Change.Web.Ui/Views/Students/Index.cshtml
@using Lead2Change.Domain.Constants
@inject Lead2Change.Services.Coaches.ICoachService _coachService
@model List<Lead2Change.Domain.Models.Student>;
@*
    ViewData["Title"] = "Index";
*@

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">



<div class="container">
    <div class="row blueHeader full-width mb-sm-3">
        <div class="col-sm-12">
            <h1 class="text-center"><strong>STUDENTS</strong></h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 searchbar ml-auto">
            <input type="text" id="myInput" onkeyup="searchFilter()" placeholder="Search for students.." class="tableInput searchbar__input" align="right">
            <button type="button" class="searchbar__button">
                <i class="material-icons">search</i>
            </button>
        </div>
    </div>

    <div class="col-sm-12">
        <table class="table table-striped table-hover table-responsive-sm fixedTable mt-sm-3 mb-0 shadow-lg">
            <thead class="blueStyle">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Date Of Birth</th>
                    <th scope="col">Email</th>
                    <th scope="col">Parent Name</th>
                    <th scope="col">Parent Email</th>
                    <th scope="col">Coach Name</th>
                    <th scope="col">Options</th>
                </tr>
            </thead>
        </table>
        <div class="tableScroll shadow-lg">
            <table class="table table-striped table-hover table-responsive-sm fixedTable mb-0 tableMin" id="myTable">
                <thead class="blueStyle d-none">
                    <tr>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {

                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StudentLastName), @Html.DisplayFor(modelItem => item.StudentFirstName)
                                </td>
                                <td>
                                    @Convert.ToDateTime(item.StudentDateOfBirth).ToString("MM/dd/yyyy")
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StudentEmail)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ParentLastName), @Html.DisplayFor(modelItem => item.ParentFirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ParentEmail)
                                </td>
                                <td>
                                    @if(item.CoachId.HasValue)
                                    {
                                        var coach = _coachService.GetCoach(item.CoachId.Value).Result;
                                        @Html.Raw($"{coach.CoachLastName} {coach.CoachFirstName}")
                                    }
                                    else
                                    {
                                        @Html.Raw("None")
                                    }
                                <td>
                                    <div class="dropdown">
                                        <button class="btn  btn-block orangeBtn mb-sm-2 dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Options</button>
                                        <div class="dropdown-menu">
                                            <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Edit","Students", new { studentId = item.Id })'">Edit</button>
                                            <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Details","Students", new { studentId = item.Id })'">Details</button>
                                            <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Index","Goals", new { studentId = item.Id })'">Student Goals</button>
                                            <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Index","Interviews", new { studentID = item.Id })'">Interviews</button>
                                            @if (item.CareerDeclarationId == Guid.Empty)
                                            {
                                                <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Create","CareerDeclaration", new { studentId = item.Id })'">Add Career</button>
                                            }
                                            else
                                            {
                                                <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Details","CareerDeclaration", new { studentId = item.Id })'">View Career</button>
                                            }
                                            <button class="dropdown-item" type="button" onclick="location.href='@Url.Action("Archive","Students", new { studentId = item.Id })'">Archive</button>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }}
                </tbody>
            </table>
        </div>
    </div>




    @if (User.IsInRole(StringConstants.RoleNameAdmin))
    {
        <div>
            <a asp-action="InterestForm"><b>Register a new student</b></a>
        </div>}
</div>

src/Lead2Change.Web.Ui/Views/Students/ThankYou.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div align="center">
    <h2>Thank You For Filling Out the Interest Form</h2>
    <p>You'll recieve a confirmation email soon. You'll be contacted soon regarding your acceptance.</p>
    <a href="https://lead2changeinc.org/">Home Page</a>
</div>