src/Lead2Change.Web.Ui/Controllers/CoachesController.cs
using Lead2Change.Domain.ViewModels;
using Lead2Change.Services.Identity;
using Lead2Change.Services.Coaches;
using Microsoft.AspNetCore.Mvc;
using Lead2Change.Domain.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Lead2Change.Domain.Constants;
using Lead2Change.Services.Students;
using Microsoft.AspNetCore.Authorization;

namespace Lead2Change.Web.Ui.Controllers
{
    [Authorize(Roles = StringConstants.RoleNameAdmin + "," + StringConstants.RoleNameCoach)]
    public class CoachesController : _BaseController
    {
        ICoachService _coachService;
        IStudentService _studentService;

        public CoachesController(IUserService identityService, ICoachService coachService, IStudentService studentService, RoleManager<AspNetRoles> roleManager, UserManager<AspNetUsers> userManager, SignInManager<AspNetUsers> signInManager) : base(identityService, roleManager, userManager, signInManager)
        {
            _coachService = coachService;
            _studentService = studentService;
        }

        [Authorize(Roles = StringConstants.RoleNameAdmin)]
        public async Task<IActionResult> Index()
        {
            return View(await _coachService.GetCoaches());
        }
        public async Task<IActionResult> AssignedIndex()
        {
            return View(await _coachService.GetCoaches());
        }


        [Authorize(Roles = StringConstants.RoleNameAdmin)]
        public async Task<IActionResult> Delete(Guid id)
        {
            var coach = await _coachService.GetCoach(id);
            if (id == Guid.Empty || coach == null)
            {
                return Error("400: Bad Request");
            }

            coach.Students = await _studentService.GetCoachStudents(id);
            foreach (var item in coach.Students)
            {
                item.CoachId = null;
            }

            await _coachService.Delete(coach);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var coachescontainer = await _coachService.GetCoach(id);

            if (id == Guid.Empty || coachescontainer == null)
            {
                return Error("400: Bad Request");
            }

            CoachViewModel model = new CoachViewModel();

            if (coachescontainer != null)
            {
                model.Id = coachescontainer.Id;
                model.CoachFirstName = coachescontainer.CoachFirstName;
                model.CoachLastName = coachescontainer.CoachLastName;
                model.CoachEmail = coachescontainer.CoachEmail;
                model.CoachPhoneNumber = coachescontainer.CoachPhoneNumber;
                model.Students = new List<Student>();
                model.Active = coachescontainer.Active;
            }

            model.Students = await _studentService.GetCoachStudents(id);

            return View(model);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var coach = await _coachService.GetCoach(id);

            if (id == Guid.Empty || coach == null)
            {
                return Error("400: Bad Request");
            }

            CoachViewModel list = new CoachViewModel()
            {
                Id = coach.Id,
                CoachFirstName = coach.CoachFirstName,
                CoachLastName = coach.CoachLastName,
                CoachPhoneNumber = coach.CoachPhoneNumber,
                CoachEmail = coach.CoachEmail,
                Active = coach.Active
            };
            return View(list);
        }

        public async Task<IActionResult> Create()
        {
            var user = await UserManager.GetUserAsync(User);
            if (User.IsInRole(StringConstants.RoleNameCoach) && user.AssociatedId != Guid.Empty)
            {
                return Error("403: You are not authorized to view this page.");
            }

            return View(new CoachViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CoachViewModel model)
        {
            if (!SignInManager.IsSignedIn(User))
            {
                return Error("401: Unauthorized");
            }

            var user = await UserManager.GetUserAsync(User);
            if (User.IsInRole(StringConstants.RoleNameCoach) && user.AssociatedId != Guid.Empty)
            {
                return Error("403: You are not authorized to view this page.");
            }

            if (ModelState.IsValid)
            {
                    Coach coach = new Coach()
                    {
                        CoachFirstName = model.CoachFirstName,
                        CoachLastName = model.CoachLastName,
                        CoachEmail = model.CoachEmail,
                        CoachPhoneNumber = model.CoachPhoneNumber,
                        Students = new List<Student>(),
                        Active = true
                    };
                    var result = await _coachService.Create(coach);
                    if (User.IsInRole(StringConstants.RoleNameCoach))
                    {
                        user.AssociatedId = result.Id;
                        await _coachService.Update(result);
                        return RedirectToAction("Index", "Students");
                }

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<IActionResult> Update(Coach model)
        {
            if (ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    Coach list = new Coach()
                    {
                        Id = model.Id,
                        CoachFirstName = model.CoachFirstName,
                        CoachLastName = model.CoachLastName,
                        CoachEmail = model.CoachEmail,
                        CoachPhoneNumber = model.CoachPhoneNumber,
                        Active = model.Active
                    };
                    var student = await _coachService.Update(list);
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // TODO: Need to add "AddStudent" method to Service
        // Change StudentService to change the CoachId
        public async Task<IActionResult> AssignStudent(Guid studentId, Guid coachId)
        {
            var coach = await _coachService.GetCoach(coachId); //check coach exists
            var student = await _studentService.GetStudent(studentId);

            student.CoachId = coachId;

            var student1 = await _studentService.Update(student);
            return RedirectToAction("AssignStudentIndex", new { id = coach.Id });
        }

        public async Task<IActionResult> AssignStudentIndex(Guid id)
        {
            Coach tempCoach = await _coachService.GetCoach(id);
            AssignStudentViewModel assignStudentViewModel = new AssignStudentViewModel()
            {
                UnassignedStudents = await _studentService.GetUnassignedStudents(),
                CurrentCoach = tempCoach
            };
            return View(assignStudentViewModel);
        }

        public async Task<IActionResult> UnassignStudent(Guid studentId)
        {
            var student = await _studentService.GetStudent(studentId);
            var tempCoachId = student.CoachId;
            student.CoachId = null;
            var student1 = await _studentService.Update(student);
            return RedirectToAction("CoachesStudents", new { id = tempCoachId });
        }
        public async Task<IActionResult> CoachesStudents(Guid id)
        {
            var user = await UserManager.GetUserAsync(User);
            if (id == Guid.Empty) id = user.AssociatedId;

            CoachViewModel model = new CoachViewModel();
            var coachescontainer = await _coachService.GetCoach(id); //check for coachescontainer=null, and all other fields

            if (id == Guid.Empty || coachescontainer == null)
            {
                return Error("400: Bad Request");
            }

            model.Id = coachescontainer.Id;
            model.CoachFirstName = coachescontainer.CoachFirstName;
            model.CoachLastName = coachescontainer.CoachLastName;
            model.CoachEmail = coachescontainer.CoachEmail;
            model.CoachPhoneNumber = coachescontainer.CoachPhoneNumber;
            model.Students = new List<Student>();
            model.Active = coachescontainer.Active;


            model.Students = await _studentService.GetCoachStudents(id);


            return View(model);
        }
        public async Task<IActionResult> InactiveCoach(Guid coachId)
        {
            var coach = await _coachService.GetCoach(coachId);
            coach.Active = false;
            var tempList = await _studentService.GetCoachStudents(coachId);
            foreach (Student s in tempList)
            {
                await UnassignStudent(s.Id);
            }
            var coach1 = await _coachService.Update(coach);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ActiveCoach(Guid coachId)
        {
            var coach = await _coachService.GetCoach(coachId);
            coach.Active = true;
            var coach1 = await _coachService.Update(coach);
            return RedirectToAction("Index");
        }
    }
}

src/Lead2Change.Web.Ui/Controllers/GoalsController.cs
using Lead2Change.Web.Ui.Models;
using Lead2Change.Services.Goals;
using Lead2Change.Services.Students;
using Microsoft.AspNetCore.Mvc;
using Lead2Change.Domain.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Lead2Change.Domain.Models;
using Lead2Change.Services.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Lead2Change.Domain.Constants;

namespace Lead2Change.Web.Ui.Controllers
{
    [Authorize(Roles = StringConstants.RoleNameAdmin + "," + StringConstants.RoleNameCoach)]
    public class GoalsController : _BaseController
    {
        private IGoalsService GoalsService;
        private IStudentService StudentService;
        public GoalsController(IUserService identityService, IGoalsService goalsService, IStudentService studentService, RoleManager<AspNetRoles> roleManager, UserManager<AspNetUsers> userManager, SignInManager<AspNetUsers> signInManager) : base(identityService, roleManager, userManager, signInManager)
        {
            this.GoalsService = goalsService;
            this.StudentService = studentService;
        }
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await GoalsService.GetGoal(id);
            GoalViewModel goal = new GoalViewModel()
            {
                Id = id,
                StudentId = result.StudentId,
                GoalSet = result.GoalSet,
                DateGoalSet = result.DateGoalSet,
                SEL = result.SEL.Split(","),
                GoalReviewDate = result.GoalReviewDate,
                WasItAccomplished = result.WasItAccomplished,
                Explanation = result.Explanation,             
            };
            return View(goal);
        }

        public async Task<IActionResult> Update(GoalViewModel model)
        {
            // Prevents null exceptions from no SEL input being selected
            string goalSEL = (model.SEL == null) ? "" : String.Join(", ", model.SEL);


            Goal goal = new Goal
            {
                GoalSet = model.GoalSet,
                StudentId = model.StudentId,
                Id = model.Id,
                DateGoalSet = model.DateGoalSet,
                SEL = goalSEL,
                GoalReviewDate = model.GoalReviewDate,
                WasItAccomplished = model.WasItAccomplished,
                Explanation = model.Explanation,
            };
            if (ModelState.IsValid)
            {
                var Goal = await GoalsService.Update(goal);
                return RedirectToAction("Index", new { studentID = model.StudentId });
            }
            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var goal = await GoalsService.GetGoal(id);

            if (goal == null)
            {
                return RedirectToAction("Create");
            }

            if (!await CanEditStudent(goal.StudentId))
            {
                return Error("403: Not authorized to view this student.");
            }
            GoalViewModel viewModel = new GoalViewModel()
            {
                Id = id,
                StudentId = goal.StudentId,
                DateGoalSet = goal.DateGoalSet,
                GoalSet = goal.GoalSet,
                SEL = goal.SEL.Split(",") ,
                GoalReviewDate = goal.GoalReviewDate,
                WasItAccomplished = goal.WasItAccomplished,
                Explanation = goal.Explanation
            };
            return View(viewModel);
        }

        /**
         * Accepts the Guid of the student that the goal is being created for
         */
        public async Task<IActionResult> Create(Guid studentID)
        {
            return View(new GoalViewModel()
            {
                StudentId = studentID,
                // This changes the initial date displayed in the chooser
                DateGoalSet = DateTime.Today,
                GoalReviewDate = DateTime.Today,
            }) ;
        }
        [HttpPost]
        public async Task<IActionResult> Register(GoalViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                // Checks to prevent null exception errors
                string goalSEL = (viewModel.SEL == null) ? "" : string.Join(", ", viewModel.SEL);
                Goal goal = new Goal()
                {
                    GoalSet = viewModel.GoalSet,
                    StudentId = viewModel.StudentId,
                    Id = viewModel.Id,
                    DateGoalSet = viewModel.DateGoalSet,
                    SEL = goalSEL,
                    GoalReviewDate = viewModel.GoalReviewDate,
                    WasItAccomplished = viewModel.WasItAccomplished,
                    Explanation = viewModel.Explanation,
                };
                // TODO: Create StudentId on user Registration
                var result = await GoalsService.Create(goal);
                return RedirectToAction("Index", new { studentID = result.StudentId });
            }
            return View("Create", viewModel);
        }

        /**
         * Note that Index takes in a studentID (it displays the goals for that student)
         * And returns a special view model which contains a list of GoalViewModels
         * And the studentID
         */
        public async Task<IActionResult> Index(Guid studentID)
        {
            List<GoalViewModel> result = new List<GoalViewModel>();
            List<Goal> goals = await GoalsService.GetGoals(studentID);
            var student1 = await StudentService.GetStudent(studentID);
            
            foreach (Goal goal in goals)
            {
                string example = goal.SEL;
                string noSpace = String.Concat(example.Where(c => !Char.IsWhiteSpace(c)));
                result.Add(new GoalViewModel()
                {
                    GoalSet = goal.GoalSet,
                    Id = goal.Id,
                    StudentId = goal.StudentId,
                    DateGoalSet = goal.DateGoalSet,
                    SEL = noSpace.Split(","),
                    GoalReviewDate = goal.GoalReviewDate,
                    WasItAccomplished = goal.WasItAccomplished,
                    Explanation = goal.Explanation

                });
            }

            return View(new GoalsAndIDViewModel(studentID)
            {
                GoalModels = result,
                Name = student1.StudentFirstName,
                isStudentActive = student1.Active,
            }) ;
        
        }

        /**
         * Handles the deletion of a goal based off the goal's id
         */
        public async Task<IActionResult> Delete(Guid id, Guid studentID)
        {
            var goal = await GoalsService.GetGoal(id);
            await GoalsService.Delete(goal);
            return RedirectToAction("Index", new { studentID = goal.StudentId });
        }

    }
}

src/Lead2Change.Web.Ui/Views/Goals/Create.cshtml
@model Lead2Change.Domain.ViewModels.GoalViewModel
@* ViewData["Title"] = "Create";
*@

<div class="row orangeHeader full-width mb-sm-3">
    <div class="col-sm-12">
        <h1 class="text-center"><strong>GOAL SETTING</strong></h1>
    </div>
</div>
<div align="center">
    <img src="~/Images/DreamExploreBuildLogo.png" />
</div>
<form asp-action="Register" class="calibri">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group d-none">
        <input asp-for="StudentId" class="form-control" />
    </div>
    <div class="form-group">
        <b><label asp-for="GoalSet" class="control-label"></label></b>
        <input required asp-for="GoalSet" class="form-control" />
        <span asp-validation-for="GoalSet" class="text-danger"></span>
    </div>
    <div class="form-group">
        <b><label asp-for="DateGoalSet" class="control-label"></label></b>
        <input asp-for="DateGoalSet" class="form-control" data-date-format="MM-dd-yyyy" type="date" placeholder="MM-dd-yyyy" />
        <span asp-validation-for="DateGoalSet" class="text-danger"></span>
    </div>
    <div class="form-group">
        <b><label asp-for="SEL" class="control-label"></label></b>
        <div class="list-group">
            <label class="list-group-item offWhiteBackground" style="border: none">
                <input class="form-check-input" name="SEL" type="checkbox" value="Self-Awareness" required />Self-Awareness - What assets do you bring to a team environment?
            </label>
            <label class="list-group-item offWhiteBackground" style="border: none">
                <input class="form-check-input" name="SEL" type="checkbox" value="Self-Management" /> Self-Management - When your class is discussing a topic and you disagree with someone else, what are your reactions?
            </label>
            <label class="list-group-item offWhiteBackground" style="border: none">
                <input class="form-check-input" name="SEL" type="checkbox" value="Social-Awareness" /> Social-Awareness - What is the single problem affecting the people of your community the most? How do you know?
            </label>
            <label class="list-group-item offWhiteBackground" style="border: none">
                <input class="form-check-input " name="SEL" type="checkbox" value="Relationship-Skills" /> Relationship-Skills - What are some examples of productive and effective relationships while working in a team?
            </label>
            <label class="list-group-item offWhiteBackground" style="border: none">
                <input class="form-check-input " name="SEL" type="checkbox" value="Responsible Decision-Making" /> Responsible Decision-Making - If you had a million dollars to address a problem/need within our community, what would you do? Who would you think about first?
            </label>
            <span asp-validation-for="SEL" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class=" row">
            <div class="form-group, col-sm-6">
                <b> <label asp-for="GoalReviewDate" class="control-label"></label></b>
                <input asp-for="GoalReviewDate" class="form-control" data-date-format="MM-dd-yyyy" type="date" placeholder="MM-dd-yyyy" />
                <span asp-validation-for="GoalReviewDate" class="text-danger"></span>
            </div>
            <div class="form-group, col-sm-6">
                <b><label asp-for="WasItAccomplished" class="control-label"></label></b>
                <select asp-for="WasItAccomplished" class="form-control" required>
                    <option disabled selected>Select A Choice</option>
                    <option value="Yes">Yes</option>
                    <option value="In Progress">This goal remains in progress</option>
                    <option value="No">No</option>
                </select>
                <span asp-validation-for="WasItAccomplished" class="text-danger"></span>

            </div>
        </div>
    </div>
    <div class="form-group, shipping">
        <b><label asp-for="Explanation" class="control-label"></label></b>
        <textarea required asp-for="Explanation" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        <span asp-validation-for="Explanation" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-submit"/>
    </div>
</form>
<div align="center">
    <input type="button" class="btn btn-outline-dark " value="Back to Goals" onclick="location.href = '@Url.Action("Index", "Goals", new { studentId = @Model.StudentId })'; this.disabled = true;" />
</div>





@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Lead2Change.Web.Ui/Views/Goals/Details.cshtml
@model Lead2Change.Domain.ViewModels.GoalViewModel
@*
    ViewData["Title"] = "Details";
*@
<div class="row orangeHeader full-width mb-sm-3">
    <div class="col-sm-12">
        <h1 class="text-center"><strong>GOAL DETAILS</strong></h1>
    </div>
</div>
<style>
    tr:nth-child(1) {
        background: #2656A5;
        color: white;
    }   
</style>
<table class="table table-striped table-hover  shadow-lg">
    <thead>
        <tr>
            <th scope="col">Info Type</th>
            <th scope="col">Info</th>
        </tr>
    </thead>
    <tbody>
        <tr class="d-none">
            <td><b>StudentId:</b> </td>
            <td>@Model.StudentId</td>
        </tr>
        <tr>
            <td><b>Goal:</b> </td>
            <td>@Model.GoalSet</td>
        </tr>
        <tr>
            <td><b>Goal Set Date:</b> </td>
            <td>@Model.DateGoalSet.ToShortDateString()</td>
        </tr>
        <tr>
            <td><b>SEL:</b> </td>
            <td>@Model.SELDisplay</td>
        </tr>
        <tr>
            <td><b>Goal Review Date: </b></td>
            <td>@Model.GoalReviewDate.ToShortDateString()</td>
        </tr>
        <tr>
            <td><b>Accomplishment State: </b></td>
            <td>@Model.WasItAccomplished</td>
        </tr>
        <tr>
            <td><b>Explanation: </b></td>
            <td>@Model.Explanation</td>
        </tr>
    </tbody>
</table>
<div>
    <input type="button" class="btn btn-outline-dark " value="Back to Goals" onclick="location.href = '@Url.Action("Index", "Goals", new { studentId = @Model.StudentId })'; this.disabled = true;" />
</div>

src/Lead2Change.Web.Ui/Views/Goals/Index.cshtml
@model Lead2Change.Domain.ViewModels.GoalsAndIDViewModel
@*
    ViewData["Title"] = "Index";
*@
<div class="container-fluid">
    @*@Lead2Change.Web.Ui.Controllers.StudentsController.GetStudent(@Model.StudentID).StudentFirstName*@
    <div class="row orangeHeader full-width mb-sm-3">
        <div class="col-sm-12">
            <h1 class="text-center" style="text-transform: uppercase"><strong>@Model.Name's Goals</strong></h1>
        </div>
    </div>
    <table class="table table-striped shadow-lg pt-2">
        <thead class="thead blueStyle">
            <tr>
                <th>
                    Goal
                </th>
                <th>
                    Explanation
                </th>
                <th>
                    Accomplishment State
                </th>
                <th>
                    Options
                </th>
            </tr>
        </thead>

        @foreach (var item in Model.GoalModels)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.GoalSet)
        </td>

        @if (item.Explanation.Length > 75)
        {
            string expla = item.Explanation.Substring(0, 74) + "...";
            <td>
                @Html.DisplayFor(modelItem => expla)
            </td>
        }
        else
        {
            <td>
                @Html.DisplayFor(modelItem => item.Explanation)
            </td>
        }

        <td>
            @Html.DisplayFor(modelItem => item.WasItAccomplished)
        </td>
        <td>
            <div class="row">
                <div class="col-sm-12">
                    <input type="button" class="btn orangeBtn btn-block mb-sm-2" value="Edit" onclick="location.href = '@Url.Action("Edit","Goals", new { id = item.Id, studentID = item.StudentId })'; this.disabled = true;" />

                </div>
            </div>
            <div class="row">
                <div class=" col-sm-12">
                    <input type="button" class="btn orangeBtn btn-block mb-sm-2" value="Details" onclick="location.href='@Url.Action("Details","Goals", new { id = item.Id, studentID = item.StudentId })'; this.disabled = true;" />

                </div>

            </div>
            <div class="row">
                <div class="col-sm-12">
                    <input type="button" class="btn btn-block orangeBtn" value="Delete" onclick="location.href = '@Url.Action("Delete","Goals", new { id = item.Id, studentID = item.StudentId })'; this.disabled = true; this.value = 'Deleting…';" />

                </div>
            </div>
        </td>
    </tr>
        }

    </table>

    <div class="row">
        <div class="col-sm-12 pb-sm-2">
            <input type="button" class="btn btn-primary" value="Create a Goal" onclick="location.href='@Url.Action("Create","Goals", new {studentID = Model.StudentID })'; this.disabled = true;" />
        </div>
    </div>
    <br />
    @if (User.IsInRole("admin"))
    {
        if (Model.isStudentActive)
        {
            <div align="center">
                <button class="btn btn-outline-dark " onclick="location.href='@Url.Action("Index", "Students")'">Back To Students</button>
            </div>
        }
        else
        {
            <div align="center">
                <button class="btn btn-outline-dark " onclick="location.href='@Url.Action("InactiveIndex", "Students")'">Back To Inactive Students</button>
            </div>
        }
    }
    else
    {
        <div align="center">
            <button class="btn btn-outline-dark " onclick="location.href='@Url.Action("CoachesStudents", "Coaches")'">Back To Students</button>
        </div>
    }
</div>