src/Lead2Change.Web.Ui/Controllers/AnswerController.cs
using Lead2Change.Services.Answers;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lead2Change.Domain.ViewModels;
using Lead2Change.Domain.Models;
using Lead2Change.Services.Interviews;
using Lead2Change.Services.Students;
using Lead2Change.Web.Ui.Models;
using Lead2Change.Services.Goals;
using Lead2Change.Services.Students;
using Microsoft.AspNetCore.Mvc;
using Lead2Change.Domain.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Lead2Change.Domain.Constants;

using Lead2Change.Domain.Models;
using Lead2Change.Services.Identity;
using Microsoft.AspNetCore.Identity;


namespace Lead2Change.Web.Ui.Controllers
{
    [Authorize(Roles = StringConstants.RoleNameAdmin + "," + StringConstants.RoleNameCoach)]
    public class AnswerController : Controller
    {

        private IAnswersService AnswersService;
        private IInterviewService _interviewsService;
        private IStudentService _studentService;

        public AnswerController(IAnswersService answersService, IInterviewService interviewsService, IStudentService studentService)
        {
            this.AnswersService = answersService;
            this._interviewsService = interviewsService;
            this._studentService = studentService;

        }
        public async Task<IActionResult> Index(Guid interviewID, Guid studentId)
        {
            var student1 = await _studentService.GetStudent(studentId);

            List<AnswersViewModel> result = new List<AnswersViewModel>();
            List<Answer> answers = await AnswersService.GetAnswers(interviewID);
            var interview1 = await _interviewsService.GetInterview(interviewID);
            foreach (Answer answer in answers)
            {
                if (answer.StudentId == studentId)
                {
                    result.Add(new AnswersViewModel()
                    {
                        AnswerString = answer.AnswerString,
                        QuestionString = answer.QuestionString,
                        Id = answer.Id,
                        StudentId = studentId,
                        QuestionId = answer.QuestionId,


                        InterviewId = answer.InterviewId,
                        StudentName = student1.StudentFirstName,
                        InterviewName = (await _interviewsService.GetInterview(interviewID)).InterviewName,
                    });
                }
            }
            return View(new StudentInterviewAndIDViewModel(interviewID)
            {
                AnswerModels = result,
                InterviewName = interview1.InterviewName,
                StudentName = student1.StudentFirstName,
                StudentID = studentId,
            }) ;

        }
        public async Task<IActionResult> Create()
        {
            return View(new AnswersViewModel());
          
        }
        public async Task<IActionResult> AnswerQuestion(Guid id, Guid studentID)
        {
           

            var result = await _interviewsService.GetInterviewAndQuestions(id);
            
            AnswerQuestionViewModel answer = new AnswerQuestionViewModel()
            {
                Id = id,
                StudentId = studentID,
                QuestionInInterviews = result,
                InterviewName = (await _interviewsService.GetInterview(id)).InterviewName,

            InterviewId = result.FirstOrDefault().Interview.Id,
              
            };
            return View(answer);
        }
        [HttpPost]
        public async Task<IActionResult> RegisterAnswerQuestion(AnswerQuestionViewModel model)
        {
            List<Student> students = await _studentService.GetActiveStudents();
            var questions = await _interviewsService.GetInterviewAndQuestions(model.InterviewId);
      
            if (ModelState.IsValid)
            {
                for (int i = 0; i < model.Answers.Count; i++)
                {
                    Answer answer = new Answer()
                    {
                        AnswerString = model.Answers[i].AnswerString,
                        QuestionString = questions[i].Question.QuestionString,
                        InterviewId = model.InterviewId,
                        StudentId = model.StudentId,
                        QuestionId = questions[i].QuestionId,
                        
                        InterviewName = (await _interviewsService.GetInterview(model.InterviewId)).InterviewName,
                        
                    };
                    var result = await AnswersService.AnswerQuestion(answer);
                    
                }
                return RedirectToAction("Index", new { interviewID = model.InterviewId, studentId = model.StudentId });


            }
            return View("Create", model);
        }
        
        public async Task<IActionResult> Register(AnswersViewModel model)
        {
            if (ModelState.IsValid)
            {
                Answer answer = new Answer()
                {
                    AnswerString = model.AnswerString,
                    QuestionString = model.QuestionString,
                    Id = model.Id,
                    StudentId = model.StudentId,
                    QuestionId = model.QuestionId,
                    StudentName = model.StudentName,

                };
                var result = await AnswersService.Create(answer);
                return RedirectToAction("Index");
            }
            return View("Create", model);
        }
        public async Task<IActionResult> Delete(Guid id, Guid studentID)
        {
            var answer = await AnswersService.GetAnswer(id);
            await AnswersService.Delete(answer);
            return RedirectToAction("Index", new { interviewID = answer.InterviewId, studentID=answer.StudentId });
        }
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await AnswersService.GetAnswer(id);
            AnswersViewModel answer = new AnswersViewModel()
            {
                AnswerString = result.AnswerString,
                QuestionString = result.QuestionString,
                Id = id,
                StudentId = result.StudentId,
                QuestionId = result.QuestionId,
                InterviewId = result.InterviewId,
            };
            return View(answer);
        }
        public async Task<IActionResult> Update(Answer model)
        {
            if (ModelState.IsValid)
            {
                var Answer = await AnswersService.Update(model);
                return RedirectToAction("Index", new { interviewID = model.InterviewId, studentID = model.StudentId });
            }

            return View(model);
        }
    }
}

src/Lead2Change.Web.Ui/Controllers/InterviewsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lead2Change.Services.Interviews;
using Lead2Change.Domain.ViewModels;
using Lead2Change.Domain.Models;
using Lead2Change.Services.Questions;
using Lead2Change.Services.QuestionInInterviews;
using Lead2Change.Services.Students;
using Microsoft.AspNetCore.Authorization;
using Lead2Change.Domain.Constants;
using Microsoft.AspNetCore.Identity;
using Lead2Change.Services.Identity;

namespace Lead2Change.Web.Ui.Controllers
{
    [Authorize(Roles = StringConstants.RoleNameAdmin + "," + StringConstants.RoleNameCoach)]
    public class InterviewsController : _BaseController
    {
        private IInterviewService _interviewsService;
        private IQuestionsService _questionService;
        private IQuestionInInterviewService _questionInInterviewService;
        private IStudentService _studentService;

        public InterviewsController(IUserService userService, IInterviewService interviewsService, IQuestionsService questionService, IQuestionInInterviewService questionInInterviewService, IStudentService studentService, RoleManager<AspNetRoles> roleManager, UserManager<AspNetUsers> userManager, SignInManager<AspNetUsers> signInManager) : base(userService, roleManager, userManager, signInManager)
        {
            _interviewsService = interviewsService;
            _questionService = questionService;
            _questionInInterviewService = questionInInterviewService;
            _studentService = studentService;
        }

        public async Task<IActionResult> Index(Guid studentID)
        {
            string studentName = string.Empty;
            if (studentID != Guid.Empty)
            {
                var student1 = await _studentService.GetStudent(studentID);
                studentName = student1.StudentFirstName;
            }
            List<InterviewViewModel> result = new List<InterviewViewModel>();
            List<Interview> interviews = await _interviewsService.GetInterviews();
            foreach (Interview interview in interviews)
            {
                result.Add(new InterviewViewModel
                {
                    InterviewName = interview.InterviewName,
                    Id = interview.Id,
                    QuestionInInterviews = interview.QuestionInInterviews,
                    StudentId = studentID,
                }) ;
            }
            return View(new InterviewAndIDViewModel(studentID)
            {
                InterviewViewModels = result,
                StudentId = studentID,
                StudentName = studentName 
            });
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var interview = await _interviewsService.GetInterview(id);
            await _interviewsService.Delete(interview);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Create()
        {
            return View(new InterviewWithQuestionsViewModel()) ;
        }
        public async Task<IActionResult> Register(InterviewWithQuestionsViewModel model, String submitButton)
        {
            if (ModelState.IsValid)
            {
                // If everything is empty, then there is nothing to create and program should return to index
                if(String.IsNullOrEmpty(model.InterviewName) && String.IsNullOrEmpty(model.QuestionText) && (String.IsNullOrEmpty(submitButton) || submitButton.Equals("Create")))
                {
                    return RedirectToAction("Index");
                }
                // Interviews with no set names default to Untitled
                model.InterviewName = (String.IsNullOrEmpty(model.InterviewName)) ? "Untitled" : model.InterviewName;
                Interview interview = await _interviewsService.Create(new Interview { InterviewName = model.InterviewName });
                // Update the viewModel's ID
                model.Id = interview.Id;
                // After the model is created, the update method handles the rest of the funcionality
                return await Update(model, submitButton, true);
            }
            return RedirectToAction("Create");
        }


        public async Task<IActionResult> Edit(Guid id)
        {
            List<QuestionInInterview> questionInInterviews = await _interviewsService.GetInterviewAndQuestions(id);
            InterviewWithQuestionsViewModel newModel = new InterviewWithQuestionsViewModel
            {
                AddedQuestions = questionInInterviews.Select(questionInInterview => questionInInterview.Question).ToList(),
                Id = id,
                InterviewName = await GetInterviewName(id),
                UnselectedQuestions = await _questionService.GetAllExcept(id)
            };
            return View("Edit", newModel);
        }

        public async Task<IActionResult> Update(InterviewWithQuestionsViewModel model, String submitButton, bool fromCreate = false)
        {
            if (ModelState.IsValid)
            {
                if (!fromCreate)
                {
                    await _interviewsService.Update(new Interview
                    {
                        Id = model.Id,
                        InterviewName = (String.IsNullOrEmpty(model.InterviewName)) ? "Untitled" : model.InterviewName,
                    }) ;
                }
                
            
                List<QuestionInInterview> questionInInterviews = await _interviewsService.GetInterviewAndQuestions(model.Id);
                model.AddedQuestions = questionInInterviews.Select(questionInInterview => questionInInterview.Question).ToList();

                // Step 2: Create and Add Question
                if (!String.IsNullOrEmpty(model.QuestionText))
                {
                    QuestionInInterview question = await AddQuestion(model.Id, model.QuestionText, model.AddedQuestions.Count + 1);
                    model.AddedQuestions.Add(question.Question);
                    model.QuestionText = null;
                }
                // Step 3: Return User to Correct View Based on the Button Pushed
                ModelState.Clear();
                return submitButton switch
                {
                    "addQuestion" => View("Edit", model),
                    "selectQuestion" => RedirectToAction("QuestionSelect", new { id = model.Id }),
                    _ => RedirectToAction("Index"),
                };
            }
            return View("Edit", model);
        }

        public async Task<IActionResult> Details(Guid id, Guid studentID)
        {
            var result = await _interviewsService.GetInterviewAndQuestions(id);
            InterviewViewModel interviewModel;
            // If there are no questions in the interview, we can't get the title from QuestionInInterviews0
            if(result == null || result.Count == 0)
            {
                var interview = await _interviewsService.GetInterview(id);
                interviewModel = new InterviewViewModel {
                    Id = id,
                    InterviewName = interview.InterviewName,
                    StudentId = studentID
                };
            }
            else
            {
                interviewModel = new InterviewViewModel()
                {
                    Id = id,
                    QuestionInInterviews = result,
                    InterviewName = result.FirstOrDefault().Interview.InterviewName,
                    StudentId = studentID
                };
            }
            return View(interviewModel);
        }

        public async Task<IActionResult> QuestionSelect(Guid id)
        {
            List<QuestionInInterview> interviewAndQuestions = await _interviewsService.GetInterviewAndQuestions(id);
            List<Question> remainingQuestions = await _questionService.GetAllExcept(id);
            InterviewWithQuestionsViewModel interview;
            if(interviewAndQuestions != null && interviewAndQuestions.Count != 0)
            {
                interview = new InterviewWithQuestionsViewModel
                {
                    AddedQuestions = interviewAndQuestions.Select(questionInInterview => questionInInterview.Question).ToList(),
                    InterviewName = interviewAndQuestions.FirstOrDefault().Interview.InterviewName,
                    Id = id,
                    UnselectedQuestions = remainingQuestions
                };
            }
            else
            {
                // If there arent any QuestionInInterviews, info must be taken from the actual interview
                var tempInterview = await _interviewsService.GetInterview(id);
                interview = new InterviewWithQuestionsViewModel
                {
                    Id = id,
                    InterviewName = tempInterview.InterviewName,
                    UnselectedQuestions = remainingQuestions
                };
            }
            
            return View(interview);
        }

        public async Task<IActionResult> SelectQuestion(Guid interviewId, Guid questionId)
        {
            // Adds an existing question to an interview
            QuestionInInterview result = await _questionInInterviewService.Create(new QuestionInInterview()
            {
                InterviewId = interviewId,
                QuestionId = questionId,
                Order = (await _interviewsService.GetInterviewAndQuestions(interviewId)).Count + 1
            });
            return RedirectToAction("QuestionSelect", new { id = interviewId });
        }
        public async Task<IActionResult> StudentsInInterview(Guid Id)
        {
            List<Student> students = null;

src/Lead2Change.Web.Ui/Views/Answer/AnswerQuestion.cshtml
@model Lead2Change.Domain.ViewModels.AnswerQuestionViewModel
@*
    ViewData["Title"] = "AnswerQuestion";
*@

<div class="container-fluid">
    <div class="row orangeHeader full-width mb-sm-3">
        <div class="col-sm-12">
            <h1 class="text-center"><strong>@Model.InterviewName.ToUpper()</strong></h1>
        </div>
    </div>

    <form asp-action="RegisterAnswerQuestion" class="calibri">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group d-none">
            <input asp-for="@Model.Id" class="form-control" />
        </div>
        <div class="form-group d-none">
            <input asp-for="@Model.StudentId" class="form-control" />
        </div>
        <div class="form-group d-none">
            <input asp-for="@Model.InterviewId" class="form-control" />
        </div>
        <div class="form-group d-none">
            <input asp-for="@Model.InterviewName" class="form-control" />
        </div>


        @for (int j = 0; j < Model.QuestionInInterviews.Count; j++)
        {

            <b>@Model.QuestionInInterviews[j].Question.QuestionString</b>


            <div class="form-group">
                <textarea asp-for="@Model.Answers[j].AnswerString" class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Your Answer" required></textarea>
                <span asp-validation-for="@Model.Answers[j].AnswerString" class="text-danger" required></span>
            </div>
        }
        <div class="form-group">
            <input type="submit" value="Submit" class="btn btn-primary" />
        </div>
    </form>
    <div align="center">
        <button class="btn btn-outline-dark " onclick="location.href='@Url.Action("Index","Interviews", new { studentID = Model.StudentId })'">Back To Your Interviews</button>
    </div>
    <br />
    <div align="center">
        <button class="btn btn-outline-dark " onclick="location.href='@Url.Action("StudentsInInterview","Interviews", new { id = Model.InterviewId })'">Back To Student Interviews</button>
    </div>


</div>

src/Lead2Change.Web.Ui/Views/Answer/Create.cshtml
@model Lead2Change.Domain.ViewModels.AnswersViewModel
@* ViewData["Title"] = "Create";
*@
<form asp-action="Register" class="calibri">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group d-none">
        <input asp-for="Id" class="form-control" />
    </div>

    <div class="container-fluid">
        <div class="form-group">
            <b><label asp-for="AnswerString" class="control-label"></label></b>
            <input asp-for="AnswerString" class="form-control" required />
            <span asp-validation-for="AnswerString" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-submit" />
        </div>
</form>
<div align="center">
    <button class="btn btn-outline-dark"><a asp-action="Index">Back to List</a></button>
</div>





@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Lead2Change.Web.Ui/Views/Answer/Edit.cshtml
@model Lead2Change.Domain.ViewModels.AnswersViewModel;
@*
    ViewData["Title"] = "Edit";
*@
<div class="row blueHeader full-width mb-sm-3">
    <div class="col-sm-12">
        <h1 class="text-center"><strong>EDIT ANSWERS</strong></h1>
    </div>
</div>
<form asp-action="Update" class="calibri">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group, d-none" display="none">
        <label asp-for="@Model.Id" class="control-label"></label>
        <input asp-for="@Model.Id" class="form-control" value=@Model.Id />
    </div>
    <div class="form-group, d-none" display="none">
        <label asp-for="@Model.StudentId" class="control-label"></label>
        <input asp-for="@Model.StudentId" class="form-control" value=@Model.StudentId />
    </div>
    <div class="form-group, d-none" display="none">
        <label asp-for="@Model.InterviewId" class="control-label"></label>
        <input asp-for="@Model.InterviewId" class="form-control" value=@Model.InterviewId />
    </div>
    <div class="form-group, d-none" display="none">
        <label asp-for="@Model.QuestionString" class="control-label"></label>
        <input asp-for="@Model.QuestionString" class="form-control" value=@Model.QuestionString />
    </div>
    <div class="form-group">
        <b><label asp-for="@Model.AnswerString" class="control-label"></label></b>
        <input asp-for="@Model.AnswerString" class="form-control" value=@Model.AnswerString required />
        <span asp-validation-for="@Model.AnswerString" class="text-danger"></span>
    </div>

    <br />
    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-submit" />
    </div>
</form>
<div align="center">
    <button class="btn btn-outline-dark " onclick="location.href='@Url.Action("Index","Answer", new {interviewID=Model.InterviewId, studentId=Model.StudentId})'">Back To List</button>
</div>

src/Lead2Change.Web.Ui/Views/Answer/Index.cshtml
@model Lead2Change.Domain.ViewModels.StudentInterviewAndIDViewModel;
@*
    ViewData["Title"] = "Index";
*@

<div class="container-fluid">

    <div class="row orangeHeader full-width mb-sm-3">
        <div class="col-sm-12">
            <h1 class="text-center"><strong>@Model.StudentName.ToUpper()'S ANSWERS FOR @Model.InterviewName.ToUpper() </strong></h1>
        </div>
    </div>
    <table class="table table-striped shadow-lg pt-2">
        <thead class="thead blueStyle">
            <tr>
                <th class="col-sm-4">
                    Question
                </th>
                <th class="col-sm-5">
                    Answer
                </th>
                <th class="col-sm-3">
                    Options
                </th>
            </tr>
        </thead>

        @foreach (var item in Model.AnswerModels)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionString)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AnswerString)
                </td>
                <td>
                    <div class="row">
                        <div class="col-sm-12">
                            <input type="button" class="btn orangeBtn btn-block mb-sm-2" value="Edit Answer" onclick="location.href='@Url.Action("Edit","Answer", new { id = item.Id })'" />

                        </div>
                    </div>



                    <div class="row">
                        <div class="col-sm-12">
                            <input type="button" class="btn btn-block orangeBtn" value="Delete Answer" onclick="location.href='@Url.Action("Delete","Answer", new { id = item.Id })'" />
                        </div>
                    </div>
                </td>
            </tr>
        }

    </table>

    <div class="row">
        <div class="col-sm-12 pb-sm-2">
            <input type="button" class="btn btn-primary" value="Student Interviews" onclick="location.href='@Url.Action("Index","Interviews")'" />
        </div>
    </div>
 
    <div align="center">
        <button class="btn btn-outline-dark " onclick="location.href='@Url.Action("Index", "Interviews", new { studentId = Model.StudentID })'">Back To @Model.StudentName's Interviews</button>
    </div>
 
</div>